networks:
  dev:
services:
  back:
    environment:
      - ConnectionStrings__Postgres=Host=db;Port=5432;Database=libdb;Username=postgres;Password=postgres
    volumes:
      - covers_data:/app/wwwroot/covers
    networks:
      - dev
    
  client:
    networks:
      - dev

  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - dev 

  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80" 
    networks:
      - dev


volumes:
  postgres_data:
  covers_data:
      