services:
  back:
    build:
      context: .
    depends_on:
      - db

  client:
    build:
      context:  ./lib-client
    

  proxy:
    image: nginx:latest
    depends_on:
      - back
      - client

  db:
    image: postgres:latest
    


